### ISSUE TITLE
Create a solid bottom level and/or unbreakable blocks

### ISSUE THREAD

**Issue by kaankaraoglu** [cribalik/mineclone#2]
• We should create a solid bottom level so that we don't go down indefinitely and end up with bedrock everywhere.
• Also, maybe stop generating new blocks on some +-z level so we don't generate unnecessary blocks when we reach bedrock? (Dunno how to handle this best).

**Comment by cribalik** [comment]
Maybe it's enough to do it like they do in the real game, where you have z 0-5 is bedrock, and then z < 0 is all air?

**Comment by cribalik** [comment]
How you can make blocks indestructible:

update_player() is where we handle the player clicking to remove blocks. There's a check on if (state.mouse_clicked), in there it casts a ray to check if there is a block in front of the player, if the ray hit a block, we call remove_block on it. An added check there on the block type (use get_blocktype) should do the trick :)
